#!/bin/zsh
# This hook is run after every virtualenv is activated.

PROMPT="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="[ %{$fg[yellow]%}`basename \"$VIRTUAL_ENV\"` %{$reset_color%}] $RPROMPT"
